- hosts: all
  tasks:
  - name: Ansible create user example.
    user:
      name: dkaplowitz
      # password: <some hash>
      comment: David Kaplowitz
      # uid: 1000
      groups: dkaplowitz,adm
      append: yes
      shell: /usr/bin/zsh
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
