- name: Add the user 'dkaplowitz' with a uid 1000 and a primary group of 'dkaplowitz'
  user:
    name: dkaplowitz
    comment: David Kaplowitz
    uid: 1000
    groups: dkaplowitz,wheel
    append: yes
    shell: /usr/bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
