#!${HOME}/.oh-my-zsh
export ZSH=${HOME}/.oh-my-zsh
export EDITOR=vim
export DOTFILES=${HOME}/git/dotfiles/vudkapz/dotfiles

ZSH_THEME="robbyrussell"

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="false"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)
plugins=(zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias ltr="ls -latr"

# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
autoload -U promptinit
promptinit

# Powerline
if [[ -r /usr/share/powerline/zsh/powerline.zsh ]]; then
      source /usr/share/powerline/zsh/powerline.zsh
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
test -e "${HOME}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" && source "${HOME}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
