#!$HOME/.oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/git/dotfiles/vudkapz/dotfiles
export TERM="xterm-256color"
export EDITOR=vim
export POWERLINE_ZSH="$HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh"
# export DATE_FMT=$(date "+%Y%m%d@%H:%M:%S")

mkcd ()
{
    mkdir -p -- "$1" &&
      cd -P -- "$1"
}

ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="false"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)
plugins=(zsh-autosuggestions)


# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:$HOME/bin"
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH=$PATH:$EC2_HOME/bin:$BLACKBOX_HOME
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


autoload -U promptinit
promptinit
# Powerline
if [[ -r $POWERLINE_ZSH ]]; then
      source $POWERLINE_ZSH
fi

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
# NOTE TO SELF: Why the fuck did I enable this? What's it for? Why does it fuck
# up my path so bad?
#[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"

test -e "$HOME/.iterm2_shell_integration.zsh" && source "$HOME/.iterm2_shell_integration.zsh"
test -e "/usr/local/Cellar/zsh-syntax-highlighting/0.5.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" && source "/usr/local/Cellar/zsh-syntax-highlighting/0.5.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
test -e "$HOME/.bin/tmuxinator.sh" && source "$HOME/.bin/tmuxinator.zsh"
# Python TLS stuff for Racerx
# You might need ~/.boto file as well
# Palantir certs
# export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
# export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
# export ca_certificates_file=/etc/pki/tls/certs/ca-bundle.crt
export PATH="/usr/local/go/bin:$PATH"
export AWS_DEFAULT_REGION=us-gov-west-1
export ANSIBLE_HOSTS=$HOME/git/dotfiles/vudkapz/dotfiles/ansible/hosts
export LESS=-RFX
# export CURL_CA_BUNDLE="/etc/pki/tls/certs/ca-bundle.crt"

# Begin aliases
if [ -f "$DOTFILES/zsh/.zsh/aliases.zsh" ]; then
    . "$DOTFILES/zsh/.zsh/aliases.zsh"
fi
# End aliases

# Begin history
if [ -f "$DOTFILES/zsh/.zsh/history.zsh" ]; then
    . "$DOTFILES/zsh/.zsh/history.zsh"
fi
# End history

# Begin history
if [ -f "$DOTFILES/zsh/.zsh/cheat.zsh" ]; then
    . "$DOTFILES/zsh/.zsh/cheat.zsh"
fi
# End history

# GPG stuff for Yubikey
if [ -f "$HOME/.gpg-agent-info" ]; then
  . "$HOME/.gpg-agent-info"
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
fi
export GPG_TTY=$(tty)
# End GPG stuff for Yubikey

PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
